### PR TITLE
1.0.1 Reorganizing by categories to add new section

### PR DESCRIPTION
**Pull request by miguelgargallo**
Thank you for submitting this pull request! We appreciate you spending the time to work on these changes.

## What is the motivation?

I modified the folder structure to allow new devs understand what is a configuration, that what is a plug and play guide, respecting the order and therminolgies

Today at Engineer university break, colleagues and me tried to follow the guide, but without success I determine to add a more comprehensive way, to let people to began a plug and play experience with this amazing and beautiful project, the thing is, we where not able to execute a command correctly with this guide, and we added a more comprehensive steps added to the rest of the guide, to allow devs to plug and play directly, today and now Surreal DB!

## What does this change do?

Allow devs a real plug-and-play experience, just out of the box, access command, and create, select and relate!

## What is your testing strategy?

No code was change, my strategy is to improve guidance papers, as I am engineer student and I use actively rust and typescript in my developments.

## Is this related to any issues?

The issue is to improve the readme experience.

## Have you read the [Contributing Guidelines](https://github.com/surrealdb/surrealdb/blob/master/CONTRIBUTING.md)?

- [🦀] I have read the [Contributing Guidelines](https://github.com/surrealdb/surrealdb/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by kearfy** [comment]
Hey, great suggestion but to be very honest I think it will only further increase complexity to contribute to the project. We opted for this file structure to keep things as simple as possible.

@tobiemh what do you think?

**Comment by miguelgargallo** [comment]
Well If don't worry, I can just simple update my guide to the community foder 👍

**Comment by miguelgargallo** [comment]
Dear @tobiemh and @kearfy here are the major update, I specially dedicate some time to turn on into a professional repo formatted and well documented! I wish you loved it!

**Review by kearfy — CHANGES_REQUESTED** [review]
Hey, sorry for the late response, had a busy few weeks 😅

Will need to reject it. By now, everybody is requesting changes for the structure, but please open a ticket for it. We cannot merge everything this way, since everybody wants a different structure. After everything is merged I'll tidy it up and actually get rid of all of the numbering overall as it's not needed.

Secondly, the SUMMARY.md file is needed as that is the entry file that mdbook looks for.

Once again thanks for the contribution!

**Comment by miguelgargallo** [comment]
> Hey, sorry for the late response, had a busy few weeks sweat_smile
> 
> Will need to reject it. By now, everybody is requesting changes for the structure, but please open a ticket for it. We cannot merge everything this way, since everybody wants a different structure. After everything is merged I'll tidy it up and actually get rid of all of the numbering overall as it's not needed.
> 
> Secondly, the SUMMARY.md file is needed as that is the entry file that mdbook looks for.
> 
> Once again thanks for the contribution!

Hey, I am only doing what @tobiemh said me! haha np

https://github.com/surrealdb/surrealdb/pull/1284?notification_referrer_id=NT_kwDOAFq_hLI0NTE3NDA1MzM1OjU5NDcyNjg#issuecomment-1264417662

**Comment by miguelgargallo** [comment]
I will be waiting for an explanation from @tobiemh if its not possible, don't worry, just want to contribute

**Comment by kearfy** [comment]
Ah, did not know that! :P
Sounds like a good plan

**Comment by miguelgargallo** [comment]
In my proposal, I separate into different main categories, third-party addons, which is community and real guides to run only surrealdb, which are official guides

**Comment by kearfy** [comment]
Hey Miguel, I discussed some things with @tobiemh. I will unfortunately need to close this PR as it does not fit within the structure and guidelines that we want to keep for the repo. I'm sorry that your great effort get's lost for now, but I will be adding proper and better guidelines in the next few days so everybody knows exactly what to expect. Thanks!

**Comment by kearfy** [comment]
Definitely feel free to add a new community guide once I've created the guidelines though!

**Comment by kearfy** [comment]
Hiya, I've just set up some proper guidelines, feel free to open a new PR. It should be much simpler now to add a new guide when just following the template file.

**Pull request closed without merging**
