### PR TITLE
Added Tutorial persistent storage

### PR DESCRIPTION
**Pull request by sewe75**
I've created a tutorial regarding persistence options - maybe one considers it useful...  
!!! Attention !!! -> This is based on the PR #8 and has to be rejected if the PR is.

### CODE REVIEW

**Comment by kearfy** [comment]
Nice tutorial, though like done in #11 we tend to keep tutorials in a single file for the simplicity of the repo. Could you refactor it into a single file (or maybe a few separate tutorials)

Sorry for the late response, busy few weeks 😅

**Review by kearfy — CHANGES_REQUESTED** [review]
Try to keep a tutorial in a single file or seperate them into multiple ones

**Comment by kearfy** [comment]
Will unfortunately need to close the PR. I am going to add proper and clear guidelines in the next few days but in this stage your contributions don't fit into the structure that we want to keep the project in. Thanks so much for your contributions never the less, feel free to open a new PR once we've added new guidelines for contributing!

**Comment by kearfy** [comment]
Hiya, I've just set up some proper guidelines, feel free to open a new PR. It should be much simpler now to add a new guide when just following the template file.

**Comment by sewe75** [comment]
Hi @kearfy Thanks for your responses!  
Busy times for me as well so I will refine it once I got some time left.

**Comment by kearfy** [comment]
Awesome, I'll see it once you're agenda has cleared a little. Thanks!

**Pull request closed without merging**
